In [3]:
import pandas as pd

df = pd.read_csv("Walmart.csv")

In [4]:
df.head()

,transaction_id,customer_id,product_id,product_name,category,quantity_sold,unit_price,transaction_date,store_id,store_location,...,customer_loyalty_level,payment_method,promotion_applied,promotion_type,weather_conditions,holiday_indicator,weekday,stockout_indicator,forecasted_demand,actual_demand
0,1,2824,843,Fridge,Electronics,3,188.46,3/31/2024 21:46,3,"Miami, FL",...,Silver,Credit Card,True,NaN,Stormy,False,Friday,True,172,179
1,2,1409,135,TV,Electronics,4,1912.04,7/28/2024 12:45,5,"Dallas, TX",...,Gold,Cash,True,Percentage Discount,Rainy,False,Monday,True,109,484
2,3,5506,391,Fridge,Electronics,4,1377.75,06/10/2024 4:55,1,"Los Angeles, CA",...,Platinum,Cash,False,NaN,Sunny,False,Tuesday,True,289,416
3,4,5012,710,Smartphone,Electronics,5,182.31,8/15/2024 1:03,5,"Miami, FL",...,Silver,Cash,True,Percentage Discount,Sunny,True,Sunday,False,174,446
4,5,4657,116,Laptop,Electronics,3,499.28,9/13/2024 0:45,6,"Chicago, IL",...,Bronze,Digital Wallet,False,NaN,Sunny,False,Thursday,True,287,469

In [5]:

df['transaction_date'] = pd.to_datetime(
    df['transaction_date'],
    errors='coerce',
    format='mixed'
)

In [6]:
df['transaction_date'].isnull().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   transaction_id          5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   product_id              5000 non-null   int64
 3   product_name            5000 non-null   object
 4   category                5000 non-null   object
 5   quantity_sold           5000 non-null   int64
 6   unit_price              5000 non-null   float64
 7   transaction_date        5000 non-null   datetime64[ns]
 8   store_id                5000 non-null   int64
 9   store_location          5000 non-null   object
 10  inventory_level         5000 non-null   int64
 11  reorder_point           5000 non-null   int64
 12  reorder_quantity        5000 non-null   int64
 13  supplier_id             5000 non-null   int64
 14  supplier_lead_time      5000 non-null   int64
 15  customer_age            5000 non-null   int64
 16  customer_gender         5000 non-null   object
 17  customer_income         5000 non-null   float64
 18  customer_loyalty_level  5000 non-null   object
 19  payment_method          5000 non-null   object
 20  promotion_applied       5000 non-null   bool
 21  promotion_type          1593 non-null   object
 22  weather_conditions      5000 non-null   object
 23  holiday_indicator       5000 non-null   bool
 24  weekday                 5000 non-null   object
 25  stockout_indicator      5000 non-null   bool
 26  forecasted_demand       5000 non-null   int64
 27  actual_demand           5000 non-null   int64
dtypes: bool(3), datetime64[ns](1), float64(2), int64(13), object(9)
memory usage: 991.3+ KB

In [8]:
df['transaction_date'] = df['transaction_date'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [9]:
df[['transaction_date']].head()

      transaction_date
0  2024-03-31 21:46:00
1  2024-07-28 12:45:00
2  2024-06-10 04:55:00
3  2024-08-15 01:03:00
4  2024-09-13 00:45:00

In [10]:
df.to_csv("Walmart_clean.csv", index=False)

In [11]:
df['revenue'] = df['quantity_sold'] * df['unit_price']

In [13]:
df.groupby('store_location')['revenue'].sum()

store_location
Chicago, IL        3156726.82
Dallas, TX         2903930.74
Los Angeles, CA    3276299.63
Miami, FL          2962567.02
New York, NY       2964077.24
Name: revenue, dtype: float64